# Generated by Django 4.1.13 on 2024-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('vehicle_class', models.CharField(choices=[('Truck', 'Truck'), ('Bus', 'Bus'), ('Van', 'Van')], max_length=50)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('insurance_details', models.TextField()),
                ('datetime_installed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Maintenance', 'Under Maintenance'), ('Emergency', 'Emergency')], default='Active', max_length=50)),
            ],
            options={
                'verbose_name': 'Vehicle Installation',
                'verbose_name_plural': 'Vehicle Installations',
            },
        ),
    ]
