# Generated by Django 4.1.13 on 2024-08-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinstallation',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='users.branch'),
        ),
    ]
