# Generated by Django 4.1.13 on 2024-08-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='installation.vehicleinstallation')),
            ],
        ),
    ]
