# Generated by Django 4.1.13 on 2024-08-29 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0003_vehicletoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
