# Generated by Django 4.1.13 on 2024-09-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_phone_number_customuser_contact_number'),
        ('installation', '0004_alter_vehicletoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinstallation',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_installations', to='users.usertypes'),
        ),
    ]
